# Generated by Django 2.0.13 on 2019-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_username', models.CharField(max_length=32)),
                ('orders_address', models.CharField(max_length=32)),
                ('orders_phone', models.CharField(max_length=32)),
                ('orders_email', models.EmailField(max_length=254)),
                ('orders_content', models.TextField()),
                ('orders_time', models.DateTimeField()),
                ('orders_designer_bool', models.IntegerField()),
                ('orders_designer_name', models.CharField(max_length=32)),
                ('orders_agreement', models.FileField(upload_to='agreement')),
                ('orders_test_time', models.CharField(max_length=108)),
                ('orders_scheme', models.FileField(upload_to='scheme')),
                ('orders_prices', models.FloatField()),
                ('orders_finish_bool', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_seller',
            field=models.ForeignKey(on_delete=True, to='Seller.Seller'),
        ),
    ]
